// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekaecixlvpaonnrpktdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrYWVjaXhsdnBhb25ucnBrdGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjE3MjAsImV4cCI6MjA2MTU5NzcyMH0.qtSWAWD2YlYq-QKKXe1-pLpBqP_i0NP9eqThdx4XlQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);